### ISSUE TITLE
Randomizing Memory Mini Game in WC 2011

### ISSUE THREAD

**Issue by UnknownDarkness** [mSpoeth/YgoNdsRandomizer#3]
Just as a suggestion, if at all possible, how about randomizing the cards obtained from the battle rewards mini game?

Maybe as options:
- Completely random
- only rare or higher cards 
- staple and/or Key cards (Book of Moon, Ally of justice catastor, etc. as well as judgement dragon, rainbow dragon, etc.)

**Comment by kathanaddaeus** [comment]
I wish I could help you on that one, but I simply don't have the time to work on this project anymore. The problem's not even implementing the features, but rather finding the files that contain the stuff to randomize. Going through the game's files is kind of a mess. There's no apparent rhyme or reason, no structure. The pack content file is in a archive file called bin2, decks are just in their own file at root. Finding out that those files hold the data that I needed to shuffle up took a lot of time, trial and error and honestly a fair bit of guessing and luck.

A short search for any files containing "memory" didn't result in any files, but knowing the dev team, it's probably using the japanese name (The rock paper scissor minigame file is called janken.pac). Maybe it's hidden somewhere in the files vaguely labeled RPG_*.pac, maybe just somewhere in a bin file, but finding the exact one is way beyond the time I have right now. If anyone's able to find out where, they're free to open an issue or create a branch to the repository. I've written down anything I know about the files in this repo's wiki.

Although that isn't the reason why I won't implement it, it would create disparity to the randomizer, as the minigame is exclusive to WCS2011 and I want to have consistent behavior for all 4 supported games.

Sorry I can't help you on that one, but maybe you can use cheats or savestates as a band-aid solution.
