### ISSUE TITLE
Trouble getting randomized WC2009 ROM

### ISSUE THREAD

**Issue by TrueNorth19** [mSpoeth/YgoNdsRandomizer#4]
Hello, I am hoping I can get some help.

I'm running the most recent ygoRandomizer JAR file and it is not giving me a NDS file at all. I have tried loading a WC2009 NDS file into the randomizer but I get nothing from it. I am sure there is something I am missing but currently I am to confused to figure it out. If I could get some help that would greatly be appreciated.

The emulator I'm using is Desmume and I have the current version of Java 8. My rom of WC2009 is the US version

**Comment by kathanaddaeus** [comment]
Hey there, happy to help!
It's really funny, I thought I tried all versions of the DS games in all regions and they all worked, but you're right, 2009 USA is the only exception. From what I can tell at first glance, something in the file structure is different in the US version, which results in trying to write data that doesn't fit anymore.

I'm not sure if I can look at fixing the randomizer in the coming days, but I did just try 2009 EU and that one works.
If you can't wait for a fix, try a EU rom for now. There aren't any region differences.

Hope that helps!

**Comment by TrueNorth19** [comment]
OK I got the 2009 EU rom. I ran the Randomizer and it was still was not working. 

But I did get the Randomizer working. In my divine wisdom when I installed Java I got the 32 bit version instead of the 64 bit. Once I installed Java64 bit the Randomizer worked perfectly.

Thanks for answering my initial question haha
